# Generated by Django 5.2.2 on 2025-06-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Menunggu Konfirmasi'), ('processing', 'Diproses'), ('ready', 'Siap Disajikan'), ('done', 'Selesai')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Tunai'), ('non-cash', 'Non-Tunai')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Belum Dibayar'), ('paid', 'Sudah Dibayar')], default='unpaid', max_length=20),
        ),
    ]
